project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("tasks.urls")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("data-browser/", include("data_browser.urls")),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.TaskListView.as_view(), name="list"),
    path("tasks/add", views.task_create, name="create"),
    path("tasks/<int:id>", views.task_item, name="item"),
    path("tasks/<int:id>/toggle", views.task_toggle, name="toggle"),
    path("tasks/<int:id>/edit", views.task_edit, name="edit"),
    path("tasks/<int:id>/delete", views.task_delete, name="delete"),
    path("tasks/clear-completed", views.clear_completed, name="clear-completed"),
]

tasks/models.py
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=50)
    complete = models.BooleanField(default=False)
    completed_at = models.DateTimeField(blank=True, null=True)
    archived = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name

tasks/forms.py
from django import forms
from tasks.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["name"]
        labels = {"name": "New Task"}

todo/forms.py
from django import forms
from todo.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["name"]
        labels = {"name": "New Task"}

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import ListView

from django_htmx.http import HttpResponseClientRefresh

from tasks.models import Task
from tasks.forms import TaskForm


class TaskListView(LoginRequiredMixin, ListView):
    queryset = Task.objects.filter(archived=False).order_by('-id')
    template_name = "tasks/task-list.html"
    context_object_name = "tasks"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = TaskForm()
        return context


@login_required
def task_create(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save()
            return render(request, 'tasks/task-list.html#task-list-item', {'task': task})


@login_required
def task_item(request, id):
    task = Task.objects.get(id=id)
    return render(request, 'tasks/task-list.html#task-list-item', {'task': task})


@login_required
def task_toggle(request, id):
    if request.method == "POST":
        task = Task.objects.get(id=id)
        if task.complete:
            task.complete = False
            task.completed_at = None
        else:
            task.complete = True
            task.completed_at = timezone.now()
        task.save()
        return render(request, 'tasks/task-list.html#task-list-item', {'task': task})


@login_required
def task_edit(request, id):
    task = Task.objects.get(id=id)
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task.name = form.cleaned_data["name"]
            task.save()
        return render(request, 'tasks/task-list.html#task-list-item', {'task': task})
    else:
        form = TaskForm(instance=task)
        form.fields["name"].label = "Task"
        context = {
            "form": form,
            "task": task,
        }
        return render(request, 'tasks/task-list.html#task-list-item-edit', context)


@login_required
def task_delete(request, id):
    if request.method == "POST":
        task = Task.objects.get(id=id)
        task.delete()

    return HttpResponse("")


@login_required
def clear_completed(request):
    if request.method == "POST":
        tasks = Task.objects.filter(complete=True)
        for task in tasks:
            task.archived = True
            task.save()
    
    return HttpResponseClientRefresh()

todo/views.py
from typing import Any, Dict
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from todo.models import Task
from todo.forms import TaskForm


@login_required
def home(request):
    tasks = Task.objects.all().order_by("id").reverse()
    form = TaskForm()
    context = {"tasks": tasks, "form": form}
    return render(request, "todo/home.html", context)


class TaskListView(LoginRequiredMixin, ListView):
    queryset = Task.objects.filter(archived=False)
    template_name = "todo/task-list.html"
    context_object_name = "tasks"
    ordering = ["-id"]

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["form"] = TaskForm()
        return context


@login_required
def task_create(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
    return redirect(reverse("todo:task-list"))


@login_required
def task_list_item(request, id):
    task = Task.objects.get(id=id)
    return render(request, "todo/task-list-item.html", {"task": task})


@login_required
def task_toggle(request, id):
    task = Task.objects.get(id=id)
    if request.method == "POST":
        if task.complete:
            task.complete = False
            task.completed_at = None
        else:
            task.complete = True
            task.completed_at = timezone.now()
        task.save()
    return redirect(reverse("todo:task-list-item", args=(task.id,)))


@login_required
def task_edit(request, id):
    task = Task.objects.get(id=id)
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task.name = form.cleaned_data["name"]
            task.save()
        return redirect(reverse("todo:task-list-item", args=(task.id,)))
    else:
        form = TaskForm(instance=task)
        form.fields["name"].label = "Task"
        context = {
            "form": form,
            "task": task,
        }
        return render(request, "todo/task-edit.html", context)


@login_required
def task_delete(request, id):
    if request.method == "POST":
        task = Task.objects.get(id=id)
        task.delete()

    return HttpResponse("")


@login_required
def clear_completed_tasks(request):
    if request.method == "POST":
        tasks = Task.objects.filter(complete=True)
        for task in tasks:
            task.archived = True
            task.save()

    return redirect(reverse("todo:task-list"))

tasks/templates/tasks/task-list.html
{% extends '../base.html' %}
{% load partials %}

{% startpartial task-list-item %}
<li id="task-item-{{ task.id }}" class="list-group-item d-flex justify-content-between align-items-center">
  <!-- Item Checkbox and Label -->
  <div class="form-group">
    <input type="checkbox"
            hx-post="{% url 'tasks:toggle' task.id %}"
            hx-target="#task-item-{{ task.id }}"
            hx-swap="outerHTML"
            class="form-check-input me-1"
            id="task-{{ task.id }}"
            value={{ task.id }}
            {% if task.complete %}checked{% endif %}>
    </input>
    <label class="form-check-label" for="task-{{ task.id }}">
      {% if task.complete %}
        <del>{{ task }}</del>
      {% else %}
        {{ task }}
      {% endif %}
    </label>
  </div>
  <!-- Option Buttons -->
  <div class="d-flex">
    <!-- Edit -->
    <button hx-get="{% url 'tasks:edit' task.id %}"
            hx-target="#task-item-{{ task.id }}"
            hx-swap="outerHTML"
            class="btn btn-sm btn-outline-primary">
      Edit
    </button>
    <!-- Delete -->
    <button hx-post="{% url 'tasks:delete' task.id %}"
            hx-target="#task-item-{{ task.id }}"
            hx-swap="outerHTML"
            class="btn btn-sm btn-outline-danger ms-2">
      Delete
    </button>
  </div>
</li>
{% endpartial %}

{% startpartial task-list-item-edit %}
<li id="task-item-{{ task.id }}" class="list-group-item d-flex justify-content-between align-items-center">
  <!-- Edit Form -->
  <form hx-post="{% url 'tasks:edit' task.id %}"
        hx-target="#task-item-{{ task.id }}"
        hx-swap="outerHTML">
      {% csrf_token %}
      {{ form.as_div }}
  </form>
  <div class="d-flex">
    <!-- Cancel -->
    <button hx-get="{% url 'tasks:item' task.id %}"
            hx-target="#task-item-{{ task.id }}"
            hx-swap="outerHTML"
            class="btn btn-sm btn-outline-primary">
      Cancel
    </button>
    <!-- Delete -->
    <button hx-post="{% url 'tasks:delete' task.id %}"
            hx-target="#task-item-{{ task.id }}"
            hx-swap="outerHTML"
            class="btn btn-sm btn-outline-danger ms-2">
      Delete
    </button>
  </div>
</li>
{% endpartial %}

{% block body %}
<h1 class="mb-3">Task List</h1>

<!-- Create Form -->
<form hx-post="{% url 'tasks:create' %}"
      hx-target="#task-list"
      hx-swap="afterbegin"
      class="mb-3">
  {% csrf_token %}
  {{ form.as_div }}
</form>

<!-- List -->
<ul id="task-list" class="list-group list-group-flush mb-3">
  {% for task in tasks %}
    {% partial task-list-item %}
  {% empty %}
    <li class="list-group-item">No tasks to display</li>
  {% endfor %}
</ul>

<!-- Clear Button -->
<button hx-post="{% url 'tasks:clear-completed' %}" class="btn btn-primary">
  Clear Completed
</button>
{% endblock %}

{% block footer %}
<script>
  let form = document.querySelector('form')
  form.addEventListener('htmx:afterRequest', () => {
    form.reset()
  })
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Matt's Fun Website</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <script src="https://unpkg.com/htmx.org@1.9.4"></script>
  {% block head %}
  {% endblock %}
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <div class="mx-auto py-3" style="max-width: 500px;">
      {% block body %}
      {% endblock %}
  </div>
  {% block footer %}
  {% endblock %}
</body>
</html>